BASE_SQUARE_SIZE = 20
STRETCH_FACTOR = 0.5

GAME_WIDTH = 900
GAME_HEIGHT = 700
COURT_DISTANCE_FROM_EDGE = 75
COURT_HEIGHT = GAME_HEIGHT - (COURT_DISTANCE_FROM_EDGE * 2)
COURT_WIDTH = GAME_WIDTH - (COURT_DISTANCE_FROM_EDGE * 2)

PADDLE_WIDTH = BASE_SQUARE_SIZE * STRETCH_FACTOR
PADDLE_DISTANCE_FROM_EDGE = PADDLE_WIDTH + 10
PADDLE_LEFT_EDGE = 0
PADDLE_RIGHT_EDGE = 1
