BASE_SQUARE_SIZE = 20
SHORT_CAR_FACTOR = 2
MEDIUM_CAR_FACTOR = 2.5
LONG_CAR_FACTOR = 3.0
CAR_LENGTH_FACTORS = [SHORT_CAR_FACTOR, MEDIUM_CAR_FACTOR, LONG_CAR_FACTOR]

GAME_WIDTH = 800
GAME_HEIGHT = 600

CAR_COLOURS = ["red", "orange", "yellow", "blue", "purple"]
CAR_SPEEDS = [BASE_SQUARE_SIZE, BASE_SQUARE_SIZE * 1.25]
CAR_TRAVEL_INCREMENT = 10
