[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.0.0"

[tool.setuptools.packages.find]
# package is laid out under `src/` — instruct setuptools to look there
where = ["src"]

[tool.setuptools]
# tell setuptools that the project package root lives in `src/`
package-dir = { "" = "src" }