name: Wish Them Happy Birthday

on:
  schedule:
    # Every day at 9am
    - cron: '0 9 * * *'
  
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the birthday wisher script
        run: python ./33-StoicQuotes/src/main.py
        env:
          BIRTHDAY_SENDER_ACC_ADDRESS: ${{ secrets.BIRTHDAY_SENDER_ACC_ADDRESS }}
          BIRTHDAY_SENDER_PASSWORD: ${{ secrets.BIRTHDAY_SENDER_PASSWORD }}
          BIRTHDAY_SENDER_EMAIL: ${{ secrets.BIRTHDAY_SENDER_EMAIL }}
          BIRTHDAY_SENDER_SMTP_SERVER: ${{ secrets.BIRTHDAY_SENDER_SMTP_SERVER }}
